/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.cliente;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import controller.Cargo;
import controller.Cliente;
import controller.Rol;
import controller.TipoDocumento;
import view.DashBoardAdso;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.JTextField;
import view.DashBoardAdso;


/**
 *
 * @author jogof
 */
public class InsertCliente extends javax.swing.JPanel {

    
    
    
    Cargo cargo = new Cargo();
    Rol rol = new Rol();
    TipoDocumento tipoDocumento = new TipoDocumento();
    public Cliente cliente = new Cliente();
    public HashMap<String, Integer> cargoHas = new HashMap<>();
    public HashMap<String, Integer> tipoDocumentoHas = new HashMap<>();
    public HashMap<String, Integer> rolHas = new HashMap<>();

    /**
     * Creates new form InsertCliente
     *
     * @throws java.sql.SQLException
     */
    public InsertCliente() throws SQLException {

        initComponents();

        //Obtenemos los HasMap para los combo box
        cargoHas = cargo.hashMapCargo();
        tipoDocumentoHas = tipoDocumento.hashMapTipoDocumento();
        rolHas = rol.hashMapRol();

        //Imprimimos un mensaje por consola
        System.out.println("Imprimiendo hasMap" + cargoHas);            //Impresion de hashmap

        //  Cargamos los comboBox
        cargarCargos();
        cargarTipoDocumento();
        cargarRol();
        limpiarCampos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        UsuarioFormjPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldPrimerNombreCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldSegundoNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTextFieldPrimerApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextFieldSegundoApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanelNickname = new javax.swing.JPanel();
        jTextFieldNickname = new javax.swing.JTextField();
        jLabelNickname = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        passAJLabel = new javax.swing.JLabel();
        jPasswordFieldA = new javax.swing.JPasswordField();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPasswordFieldB = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        jComboBoxRol = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        UsuarioFormjPanel1 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jTextFieldIdentificacion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jComboBoxTipoDocumento = new javax.swing.JComboBox<>();
        jPanel17 = new javax.swing.JPanel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        jTextField17 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxCargo = new javax.swing.JComboBox<>();
        jPanel15 = new javax.swing.JPanel();
        jTextFieldRazonSocial = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jToggleButtonIngresarCliente = new javax.swing.JToggleButton();
        jButtonInput = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setPreferredSize(new java.awt.Dimension(900, 600));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Ingreso de clientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(3757, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(326, 326, 326))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);

        UsuarioFormjPanel.setAutoscrolls(true);
        UsuarioFormjPanel.setPreferredSize(new java.awt.Dimension(800, 300));

        jPanel3.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel2.setText("Primer Nombre");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jTextFieldPrimerNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrimerNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        UsuarioFormjPanel.add(jPanel3);

        jPanel4.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel3.setText("Segundo Nombre");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        UsuarioFormjPanel.add(jPanel4);

        jPanel6.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel5.setText("Primer Apellido");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jTextFieldPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        UsuarioFormjPanel.add(jPanel6);

        jPanel5.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel4.setText("Segundo Apellido");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 16));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jTextFieldSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        UsuarioFormjPanel.add(jPanel5);

        jPanelNickname.setMinimumSize(new java.awt.Dimension(200, 0));
        jPanelNickname.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabelNickname.setText("NickName ");

        javax.swing.GroupLayout jPanelNicknameLayout = new javax.swing.GroupLayout(jPanelNickname);
        jPanelNickname.setLayout(jPanelNicknameLayout);
        jPanelNicknameLayout.setHorizontalGroup(
            jPanelNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNicknameLayout.createSequentialGroup()
                .addComponent(jLabelNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jTextFieldNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelNicknameLayout.setVerticalGroup(
            jPanelNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNicknameLayout.createSequentialGroup()
                .addGroup(jPanelNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNickname))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        UsuarioFormjPanel.add(jPanelNickname);

        jPanel10.setPreferredSize(new java.awt.Dimension(320, 25));

        jLabel9.setText("Email");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jTextFieldEmail)
                .addContainerGap())
        );

        UsuarioFormjPanel.add(jPanel10);

        passAJLabel.setText("Password");

        jPasswordFieldA.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(passAJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passAJLabel)
                    .addComponent(jPasswordFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        UsuarioFormjPanel.add(jPanel11);

        jPanel12.setPreferredSize(new java.awt.Dimension(320, 25));

        jLabel11.setText("ConfirmarPasswod");

        jPasswordFieldB.setText("jPasswordField2");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPasswordFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jPasswordFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        UsuarioFormjPanel.add(jPanel12);

        jPanel7.setPreferredSize(new java.awt.Dimension(300, 34));

        jComboBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Rol de Cliente");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(jComboBoxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        UsuarioFormjPanel.add(jPanel7);

        jPanel2.add(UsuarioFormjPanel);

        UsuarioFormjPanel1.setAutoscrolls(true);
        UsuarioFormjPanel1.setPreferredSize(new java.awt.Dimension(800, 300));

        jPanel16.setMinimumSize(new java.awt.Dimension(300, 0));
        jPanel16.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel14.setText("Identificacion ");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldIdentificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        UsuarioFormjPanel1.add(jPanel16);

        jPanel26.setMinimumSize(new java.awt.Dimension(200, 0));
        jPanel26.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel23.setText("Tipo Documento");
        jLabel23.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jComboBoxTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxTipoDocumento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        UsuarioFormjPanel1.add(jPanel26);

        jPanel17.setMinimumSize(new java.awt.Dimension(350, 0));
        jPanel17.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel15.setText("Dirección");
        jLabel15.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        UsuarioFormjPanel1.add(jPanel17);

        jPanel18.setMinimumSize(new java.awt.Dimension(350, 0));
        jPanel18.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel16.setText("Teléfono");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        UsuarioFormjPanel1.add(jPanel18);

        jPanel22.setMinimumSize(new java.awt.Dimension(200, 0));
        jPanel22.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel20.setText("Email");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField17))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        UsuarioFormjPanel1.add(jPanel22);

        jPanel14.setMinimumSize(new java.awt.Dimension(200, 0));
        jPanel14.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel12.setText("Cargo");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jComboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        UsuarioFormjPanel1.add(jPanel14);

        jPanel15.setMinimumSize(new java.awt.Dimension(300, 0));
        jPanel15.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel13.setText("Razon Social");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jTextFieldRazonSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        UsuarioFormjPanel1.add(jPanel15);

        jPanel2.add(UsuarioFormjPanel1);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jToggleButtonIngresarCliente.setText("Ingresar");
        jToggleButtonIngresarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonIngresarClienteActionPerformed(evt);
            }
        });
        jPanel13.add(jToggleButtonIngresarCliente);

        jButtonInput.setText("Input");
        jButtonInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInputActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                .addContainerGap(3913, Short.MAX_VALUE)
                .addComponent(jButtonUpdate)
                .addGap(18, 18, 18)
                .addComponent(jButtonLimpiar)
                .addGap(26, 26, 26)
                .addComponent(jButtonInput)
                .addGap(67, 67, 67)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonInput)
                        .addComponent(jButtonLimpiar)
                        .addComponent(jButtonUpdate)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(jPanel25, java.awt.BorderLayout.SOUTH);
        add(jScrollPane1, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonIngresarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonIngresarClienteActionPerformed
        // TODO add your handling code here:

        int id_cliente;
        var cargoSeleccionado = jComboBoxCargo.getSelectedItem();
        var rolSeleccionado = jComboBoxRol.getSelectedItem();
        int id_rol = rolHas.get(rolSeleccionado);
        var tipoDocumentoSeleccionado = jComboBoxTipoDocumento.getSelectedItem();
        var id_cargo = cargoHas.get(cargoSeleccionado);
        var id_tipoDocumento = tipoDocumentoHas.get(tipoDocumentoSeleccionado);
        //var id_tipoDocumento = tipoDocumentoHas.get(tipoDocumentoSeleccionado);

        try {
            //Datos de Usuario
            cliente.setNickName_usuario(jTextFieldNickname.getText());
            cliente.setPrimerNombre_usuario(jTextFieldPrimerNombreCliente.getText());
            cliente.setSegundoNombre_usuario(jTextFieldSegundoNombre.getText());
            cliente.setPrimerApellido_usuario(jTextFieldPrimerApellido.getText());
            cliente.setSegundoApellido_usuario(jTextFieldSegundoApellido.getText());
            cliente.setEmail_usuario(jTextFieldEmail.getText());
            char[] passChars = jPasswordFieldA.getPassword();
            String psw_usuario = new String(passChars);
            cliente.setPsw_usuario(psw_usuario);
            cliente.rol.setId_rol(id_rol);

            cliente.tipoDocumento.setId_tipoDocumento(id_tipoDocumento);

            //  Datos de Cliente
            cliente.setRazonSocial_cliente(jTextFieldRazonSocial.getText());
            cliente.cargo.setId_cargo(id_cargo);
            cliente.setDireccion_cliente(jTextFieldDireccion.getText());
            int telefonoCliente = Integer.parseInt(jTextFieldTelefono.getText());
            cliente.setTelefono_cliente(telefonoCliente);
            cliente.tipoDocumento.setId_tipoDocumento(id_tipoDocumento);
            int documentoCliente = Integer.parseInt(jTextFieldIdentificacion.getText().trim());
            cliente.setDocumento_cliente(documentoCliente);
            id_cliente = cliente.inputCliente(cliente, cliente);

            if (id_cliente >= 0) {
                System.out.println("Cliente registrado" + id_cliente);

                //Ejecutar metodo para lismpiar y repintar pantalla
            } else {
                System.err.println("No se pudo ingresar CLiente");
            }
            JOptionPane.showMessageDialog(null, "Cargo seleccionado: " + cargoSeleccionado
                    + "\n El del HashMap del cargo: " + id_cargo
                    + "\n Documento seleccionado: " + tipoDocumentoSeleccionado
                    + "\n El del HashMap del codumento: " + id_tipoDocumento
                    + "\n Nombre de la casilla de texto: " + cliente.getPrimerNombre_usuario()
                    + cliente.toString());

        } catch (Exception e) {
            System.err.println("Errot: " + e.getMessage());
        }
        finally{
                        ;
    }

    }//GEN-LAST:event_jToggleButtonIngresarClienteActionPerformed

    private void jButtonInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInputActionPerformed
        // TODO add your handling code here:
        int id_cliente;
        var cargoSeleccionado = jComboBoxCargo.getSelectedItem();
        var rolSeleccionado = jComboBoxRol.getSelectedItem();
        int id_rol = rolHas.get(rolSeleccionado);
        var tipoDocumentoSeleccionado = jComboBoxTipoDocumento.getSelectedItem();
        var id_cargo = cargoHas.get(cargoSeleccionado);
        var id_tipoDocumento = tipoDocumentoHas.get(tipoDocumentoSeleccionado);
        //var id_tipoDocumento = tipoDocumentoHas.get(tipoDocumentoSeleccionado);

        try {
            //Datos de Usuario
            cliente.setNickName_usuario(jTextFieldNickname.getText());
            cliente.setPrimerNombre_usuario(jTextFieldPrimerNombreCliente.getText());
            cliente.setSegundoNombre_usuario(jTextFieldSegundoNombre.getText());
            cliente.setPrimerApellido_usuario(jTextFieldPrimerApellido.getText());
            cliente.setSegundoApellido_usuario(jTextFieldSegundoApellido.getText());
            cliente.setEmail_usuario(jTextFieldEmail.getText());
            char[] passChars = jPasswordFieldA.getPassword();
            String psw_usuario = new String(passChars);
            cliente.setPsw_usuario(psw_usuario);
            cliente.rol.setId_rol(id_rol);

            cliente.tipoDocumento.setId_tipoDocumento(id_tipoDocumento);

            //  Datos de Cliente
            cliente.setRazonSocial_cliente(jTextFieldRazonSocial.getText());
            cliente.cargo.setId_cargo(id_cargo);
            cliente.setDireccion_cliente(jTextFieldDireccion.getText());
            int telefonoCliente = Integer.parseInt(jTextFieldTelefono.getText());
            cliente.setTelefono_cliente(telefonoCliente);
            cliente.tipoDocumento.setId_tipoDocumento(id_tipoDocumento);
            int documentoCliente = Integer.parseInt(jTextFieldIdentificacion.getText().trim());
            cliente.setDocumento_cliente(documentoCliente);
            id_cliente = cliente.inputCliente(cliente, cliente);

            if (id_cliente >= 0) {
                System.out.println("Cliente registrado" + id_cliente);

                //Ejecutar metodo para lismpiar y repintar pantalla
            } else {
                System.err.println("No se pudo ingresar CLiente");
            }
            JOptionPane.showMessageDialog(null, "Cargo seleccionado: " + cargoSeleccionado
                    + "\n El del HashMap del cargo: " + id_cargo
                    + "\n Documento seleccionado: " + tipoDocumentoSeleccionado
                    + "\n El del HashMap del codumento: " + id_tipoDocumento
                    + "\n Nombre de la casilla de texto: " + cliente.getPrimerNombre_usuario()
                    + cliente.toString());

        } catch (Exception e) {
            System.err.println("Errot: " + e.getMessage());
        }


    }//GEN-LAST:event_jButtonInputActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:

        limpiarCampos();

    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        
      
        
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    /**
     * *
     * Método para cargar ComboBox Cargos
     *
     * @throws SQLException
     * @return void Carga items del comboBox
     */
    final void cargarCargos() throws SQLException {
        jComboBoxCargo.removeAllItems();
        for (Cargo c : cargo.listarCargos()) {
            //cargoJCombo.addItem((Integer.toString( c.getId_cargo())));        //para listar por id y utilizar Int
            jComboBoxCargo.addItem(c.getCargo());                                  //Lo usamos con String
        }
    }

    final void cargarRol() throws SQLException {
        jComboBoxRol.removeAllItems();
        for (Rol r : rol.listarRol()) {
            jComboBoxRol.addItem(r.getDescripcion_rol());
        }

    }

    /**
     * *
     * @return void carga los ComboBox de TipoDocumento
     */
    final void cargarTipoDocumento() {
        jComboBoxTipoDocumento.removeAllItems();
        for (TipoDocumento type : tipoDocumento.listarTipoDocumento()) {
            jComboBoxTipoDocumento.addItem(type.getTipoDocumento());                        //Para trabajar con String                      
            //jComboBoxTipoDocumento.addItem(Integer.toString(type.getId_tipoDocumento())); //Solo recibe un Integer no recigbe Integer
            //identificacionJTextField.add(type);                                           //No funciona agregandole el objeto
        }
    }

    final void limpiarCampos() {
        jTextFieldDireccion.setText("");
        jTextFieldPrimerNombreCliente.setText("");
        jTextFieldSegundoNombre.setText("");
        jTextField17.setText("");
        
        jTextFieldEmail.setText("");
        jTextFieldIdentificacion.setText("");
        jTextFieldNickname.setText("");
        jTextFieldPrimerApellido.setText("");
        jTextFieldPrimerNombreCliente.setText("");
        jTextFieldRazonSocial.setText("");;
        jTextFieldSegundoApellido.setText("");;
        jTextFieldSegundoNombre.setText("");;
        jTextFieldTelefono.setText("");
       jPasswordFieldA.setText("");
       jPasswordFieldB.setText("");
       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UsuarioFormjPanel;
    private javax.swing.JPanel UsuarioFormjPanel1;
    private javax.swing.JButton jButtonInput;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxCargo;
    private javax.swing.JComboBox<String> jComboBoxRol;
    private javax.swing.JComboBox<String> jComboBoxTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNickname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelNickname;
    private javax.swing.JPasswordField jPasswordFieldA;
    private javax.swing.JPasswordField jPasswordFieldB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIdentificacion;
    private javax.swing.JTextField jTextFieldNickname;
    private javax.swing.JTextField jTextFieldPrimerApellido;
    private javax.swing.JTextField jTextFieldPrimerNombreCliente;
    private javax.swing.JTextField jTextFieldRazonSocial;
    private javax.swing.JTextField jTextFieldSegundoApellido;
    private javax.swing.JTextField jTextFieldSegundoNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JToggleButton jToggleButtonIngresarCliente;
    private javax.swing.JLabel passAJLabel;
    // End of variables declaration//GEN-END:variables
}
