/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.colaborador;

import conexion.Conexion;
import controller.Cargo;
import controller.Rol;
import controller.TipoDocumento;
import java.sql.SQLException;
import controller.Cargo;
import controller.TipoDocumento;
import controller.Rol;
import controller.Stakeholder;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.HashMap;
import javax.swing.JOptionPane;
import view.DashBoardAdso;
import view.cliente.UpdateCliente;
//import static view.cliente.UpdateCliente.clienteUpdateFrm;

/**
 *
 * @author jogof
 */
public class UpdateStakeholder extends javax.swing.JPanel {

    Rol rol = new Rol();
    Cargo cargo = new Cargo();
    TipoDocumento tipoDocumento = new TipoDocumento();

    public Stakeholder stakeholder = new Stakeholder();
    public static Stakeholder stakeholderUpdateFrm = new Stakeholder();
    //DashBoardAdso dashPruebaAdso = new DashBoardAdso();
    HashMap<String, Integer> cargoHas = new HashMap<>();
    HashMap<String, Integer> rolHas = new HashMap<>();
    HashMap<String, Integer> tipoDocumentoHas = new HashMap<>();

    /**
     * Creates new form InsertStakeholder - Constructor -
     */
    public UpdateStakeholder() throws SQLException {

        initComponents();
        limpiarCampos();

        //  HashMaps de los combBox
        cargoHas = cargo.hashMapCargo();
        rolHas = rol.hashMapRol();
        tipoDocumentoHas = tipoDocumento.hashMapTipoDocumento();

        //      Cargamos los comboBox
        //cargarCargos();
        //cargarTipoDocumento();
        //cargarRol();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        UsuarioFormjPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jTextFieldPrimerNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jTextFieldSegundoNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jTextFieldPrimerApellido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jTextFieldSegundoApellido = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxRol = new javax.swing.JComboBox<>();
        jPanelNickname1 = new javax.swing.JPanel();
        jTextFieldNickname = new javax.swing.JTextField();
        jLabelNickname1 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        passAJLabel1 = new javax.swing.JLabel();
        jPasswordFieldA = new javax.swing.JPasswordField();
        jPanel17 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPasswordFieldB = new javax.swing.JPasswordField();
        UsuarioFormjPanel2 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jTextFieldIdentificacion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jComboBoxTipoDocumento = new javax.swing.JComboBox<>();
        jPanel23 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxCargo = new javax.swing.JComboBox<>();
        jPanel25 = new javax.swing.JPanel();
        jButtonUpdate = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonCargarDatos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(900, 800));
        setLayout(new java.awt.BorderLayout());

        jPanelTitulo.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanelTitulo.setPreferredSize(new java.awt.Dimension(900, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Actualización de Colaboradores");

        javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
        jPanelTitulo.setLayout(jPanelTituloLayout);
        jPanelTituloLayout.setHorizontalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanelTituloLayout.setVerticalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanelTitulo, java.awt.BorderLayout.NORTH);
        jPanelTitulo.getAccessibleContext().setAccessibleName("");

        jPanel1.setMaximumSize(new java.awt.Dimension(700, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 300));
        jPanel1.setRequestFocusEnabled(false);

        UsuarioFormjPanel1.setAutoscrolls(true);
        UsuarioFormjPanel1.setPreferredSize(new java.awt.Dimension(800, 200));

        jPanel8.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel7.setText("Primer Nombre");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jTextFieldPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        UsuarioFormjPanel1.add(jPanel8);

        jPanel9.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel8.setText("Segundo Nombre");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        UsuarioFormjPanel1.add(jPanel9);

        jPanel13.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel10.setText("Primer Apellido");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jTextFieldPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        UsuarioFormjPanel1.add(jPanel13);

        jPanel14.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel12.setText("Segundo Apellido");
        jLabel12.setPreferredSize(new java.awt.Dimension(100, 16));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jTextFieldSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        UsuarioFormjPanel1.add(jPanel14);

        jPanel7.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel6.setText("Rol");

        jComboBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(49, 49, 49)
                .addComponent(jComboBoxRol, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jComboBoxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        UsuarioFormjPanel1.add(jPanel7);

        jPanelNickname1.setMinimumSize(new java.awt.Dimension(200, 0));
        jPanelNickname1.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabelNickname1.setText("NickName ");

        javax.swing.GroupLayout jPanelNickname1Layout = new javax.swing.GroupLayout(jPanelNickname1);
        jPanelNickname1.setLayout(jPanelNickname1Layout);
        jPanelNickname1Layout.setHorizontalGroup(
            jPanelNickname1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNickname1Layout.createSequentialGroup()
                .addComponent(jLabelNickname1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jTextFieldNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelNickname1Layout.setVerticalGroup(
            jPanelNickname1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNickname1Layout.createSequentialGroup()
                .addGroup(jPanelNickname1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNickname1))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        UsuarioFormjPanel1.add(jPanelNickname1);

        jPanel15.setPreferredSize(new java.awt.Dimension(600, 25));

        jLabel13.setText("Email");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)))
        );

        UsuarioFormjPanel1.add(jPanel15);

        jPanel16.setPreferredSize(new java.awt.Dimension(350, 28));

        passAJLabel1.setText("Password");

        jPasswordFieldA.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(passAJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passAJLabel1)
                    .addComponent(jPasswordFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        UsuarioFormjPanel1.add(jPanel16);

        jPanel17.setPreferredSize(new java.awt.Dimension(350, 28));

        jLabel14.setText("ConfirmarPasswod");

        jPasswordFieldB.setText("jPasswordField2");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPasswordFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jPasswordFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        UsuarioFormjPanel1.add(jPanel17);

        jPanel1.add(UsuarioFormjPanel1);

        UsuarioFormjPanel2.setAutoscrolls(true);
        UsuarioFormjPanel2.setPreferredSize(new java.awt.Dimension(800, 120));

        jPanel19.setMinimumSize(new java.awt.Dimension(300, 0));
        jPanel19.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel16.setText("Identificacion ");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldIdentificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        UsuarioFormjPanel2.add(jPanel19);

        jPanel26.setMinimumSize(new java.awt.Dimension(200, 0));
        jPanel26.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel23.setText("Tipo Documento");
        jLabel23.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jComboBoxTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxTipoDocumento, 0, 182, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        UsuarioFormjPanel2.add(jPanel26);

        jPanel23.setMinimumSize(new java.awt.Dimension(200, 0));
        jPanel23.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel19.setText("Cargo");
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jComboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        UsuarioFormjPanel2.add(jPanel23);

        jPanel1.add(UsuarioFormjPanel2);

        jPanel25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel25.setPreferredSize(new java.awt.Dimension(600, 79));

        jButtonUpdate.setText("Actualizar Cliente");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("Limpiar formulario");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonCargarDatos.setText("Cargar formulario");
        jButtonCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarDatosActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jButtonCargarDatos))
                .addGap(18, 18, 18)
                .addComponent(jButtonLimpiar)
                .addGap(26, 26, 26)
                .addComponent(jButtonUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonLimpiar)
                    .addComponent(jButtonCargarDatos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        jPanel1.add(jPanel25);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // Acción del botón UpDate o actualizar CLiente:
        if (jTextFieldEmail != null && stakeholderUpdateFrm.getId_stakeholder() != 0) {

            JOptionPane.showMessageDialog(null, "Dato almacenado: " + stakeholderUpdateFrm);
            var cargoSeleccionado = jComboBoxCargo.getSelectedItem();
            var rolSeleccionado = jComboBoxRol.getSelectedItem();
            int id_rol = rolHas.get(rolSeleccionado);       //  Obtenemos el Id del HashMap
            var tipoDocumentoSeleccionado = jComboBoxTipoDocumento.getSelectedItem();
            var id_cargo = cargoHas.get(cargoSeleccionado);
            var id_tipoDocumento = tipoDocumentoHas.get(tipoDocumentoSeleccionado);
            //var id_tipoDocumento = tipoDocumentoHas.get(tipoDocumentoSeleccionado);

            try {
                //Datos de Usuario
                stakeholderUpdateFrm.setNickName_usuario(jTextFieldNickname.getText());
                stakeholderUpdateFrm.setPrimerNombre_usuario(jTextFieldPrimerNombre.getText());
                stakeholderUpdateFrm.setSegundoNombre_usuario(jTextFieldSegundoNombre.getText());
                stakeholderUpdateFrm.setPrimerApellido_usuario(jTextFieldPrimerApellido.getText());
                stakeholderUpdateFrm.setSegundoApellido_usuario(jTextFieldSegundoApellido.getText());
                stakeholderUpdateFrm.setEmail_usuario(jTextFieldEmail.getText());
                char[] passChars = jPasswordFieldA.getPassword();
                String psw_usuario = new String(passChars);
                stakeholderUpdateFrm.setPsw_usuario(psw_usuario);
                stakeholderUpdateFrm.setId_rol_usuario(id_rol);

                //  Datos de Cliente
                stakeholderUpdateFrm.setId_tipoDocumento_stakeholder(id_tipoDocumento);

                int documentoStakeholder = Integer.parseInt(jTextFieldIdentificacion.getText().trim());
                stakeholderUpdateFrm.setDocumento_stakeholder(documentoStakeholder);
                boolean update = stakeholderUpdateFrm.updateStakeholder(stakeholderUpdateFrm, stakeholderUpdateFrm);

                if (update = true) {
                    System.out.println("Cliente Actualizado" + update);

                    //Ejecutar metodo para lismpiar y repintar pantalla
                } else {
                    System.err.println("No se pudo Actualizar el CLiente");
                }
                JOptionPane.showMessageDialog(null, "Cliente Enviado a : " + stakeholderUpdateFrm.toString());

            } catch (Exception e) {
                System.err.println("Errot: " + e.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(null, "No se ha cargado ningun campo"
                    + "\n Debe Acceder al listado de clientes para seleccionar una acción");
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        try {
            limpiarCampos();
            stakeholderUpdateFrm = null;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex);

        }
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarDatosActionPerformed
        try {
            // TODO add your handling code here:
            System.out.println("Stakeholder Update frm desde el boton -" + stakeholderUpdateFrm.toString());
            //limpiarCampos();
            setearCamposStakeholderFrm(stakeholderUpdateFrm);
            JOptionPane.showMessageDialog(null, "Accionando Boton Cargar Datos: " + stakeholderUpdateFrm.toString());
        } catch (Exception ex) {
            //Logger.getLogger(UpdateStakeholder.class.getName()).log(Level.SEVERE, null, ex);
            java.util.logging.Logger.getLogger(UpdateStakeholder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error al Cargar los datos" + ex.getMessage());

        }
    }//GEN-LAST:event_jButtonCargarDatosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(null, "evento boton:" + stakeholderUpdateFrm.toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * *
     * Método para cargar ComboBox Cargos
     *
     * @throws SQLException
     * @return void Carga items del comboBox
     */
    final void cargarCargos() throws SQLException {
        jComboBoxCargo.removeAllItems();
        for (Cargo c : cargo.listarCargos()) {
            //cargoJCombo.addItem((Integer.toString( c.getId_cargo())));        //para listar por id y utilizar Int
            jComboBoxCargo.addItem(c.getCargo());                                  //Lo usamos con String
        }
    }

    /**
     * *
     * @return void carga los ComboBox de TipoDocumento
     */
    final void cargarTipoDocumento() {
        jComboBoxTipoDocumento.removeAllItems();
        for (TipoDocumento type : tipoDocumento.listarTipoDocumento()) {
            jComboBoxTipoDocumento.addItem(type.getTipoDocumento());                        //Para trabajar con String                      
            //jComboBoxTipoDocumento.addItem(Integer.toString(type.getId_tipoDocumento())); //Solo recibe un Integer no recigbe Integer
            //identificacionJTextField.add(type);                                           //No funciona agregandole el objeto
        }
    }

    final void cargarRol() throws SQLException {
        jComboBoxRol.removeAllItems();
        for (Rol r : rol.listarRol()) {
            jComboBoxRol.addItem(r.getDescripcion_rol());
        }
    }

    public void limpiarCampos() throws SQLException {

        jTextFieldPrimerNombre.setText("");
        jTextFieldSegundoNombre.setText("");
        jTextFieldEmail.setText("");
        jTextFieldIdentificacion.setText("");
        jTextFieldNickname.setText("");
        jTextFieldPrimerApellido.setText("");
        jTextFieldPrimerNombre.setText("");
        jTextFieldSegundoApellido.setText("");;
        jTextFieldSegundoNombre.setText("");;
        jPasswordFieldA.setText("");
        jPasswordFieldB.setText("");
        cargarRol();

        //dashPruebaAdso.goToDashboard();
    }

    public void setearCamposStakeholderFrm(Stakeholder s) throws SQLException {

        try {
            if (s != null) {
                stakeholderUpdateFrm = s;
                setFrm();
                setFrm();

                //DashBoardAdso.dashboard.repaint();
            } else {
                JOptionPane.showMessageDialog(null, "No hay datos en memoria");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No hay datos en memoria. Error: " + e.getMessage());
        }

    }

    public void setFields(Stakeholder s) throws SQLException {

        try {
            if (s != null) {
                stakeholderUpdateFrm = s;
                //setFrm();

                System.out.println("Impriendo desde la funcion setFields con ingreso de Stakeholder" + stakeholderUpdateFrm.toString());

                //  Datos de Usuario
                jTextFieldPrimerNombre.setText(stakeholderUpdateFrm.getPrimerNombre_usuario());

                jTextFieldSegundoNombre.setText(stakeholderUpdateFrm.getSegundoNombre_usuario());
                jTextFieldEmail.setText(stakeholderUpdateFrm.getEmail_usuario());
                jTextFieldIdentificacion.setText(Integer.toString(this.stakeholderUpdateFrm.getDocumento_stakeholder()));
                jTextFieldNickname.setText(stakeholderUpdateFrm.getNickName_usuario());
                jTextFieldPrimerApellido.setText(stakeholderUpdateFrm.getPrimerApellido_usuario());
                jTextFieldSegundoApellido.setText(stakeholderUpdateFrm.getSegundoApellido_usuario());;

                jPasswordFieldA.setText("");
                jPasswordFieldB.setText("");
                String tipoDocumento = stakeholderUpdateFrm.tipoDocumento.getTipoDocumento();
                jComboBoxTipoDocumento.setSelectedItem(tipoDocumento);
                String cargo = stakeholderUpdateFrm.cargo.getCargo();
                jComboBoxCargo.setSelectedItem(cargo);
                String rol = stakeholderUpdateFrm.rol.getDescripcion_rol();
                jComboBoxRol.setSelectedItem(rol);

                JOptionPane.showMessageDialog(null, "Panel de prueba update frm: " + stakeholderUpdateFrm.getPrimerNombre_usuario() + ""
                        + " \n " + stakeholderUpdateFrm.toString());

                //DashBoardAdso.dashboard.repaint();
            } else {
                JOptionPane.showMessageDialog(null, "No hay datos en memoria");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No hay datos en memoria. Error: " + e.getMessage());
        }

    }

    public void setFrm() throws SQLException {
        //limpiarCampos();
        //clienteUpdateFrm = c;

        //JOptionPane.showMessageDialog(null, "SetFields Cliente " + c.toString());
        System.out.println("  ");
        System.out.println("Impriendo desde setFrm " + stakeholderUpdateFrm.toString());
        //jTextFieldDireccion.setText(stakeholderUpdateFrm.getDireccion_cliente());
        jTextFieldPrimerNombre.setText(stakeholderUpdateFrm.getPrimerNombre_usuario());
        jTextFieldSegundoNombre.setText(stakeholderUpdateFrm.getSegundoNombre_usuario());
        jTextFieldEmail.setText(stakeholderUpdateFrm.getEmail_usuario());
        jTextFieldIdentificacion.setText(Integer.toString(stakeholderUpdateFrm.getDocumento_stakeholder()));
        jTextFieldNickname.setText(stakeholderUpdateFrm.getNickName_usuario());
        jTextFieldPrimerApellido.setText(stakeholderUpdateFrm.getPrimerApellido_usuario());
        jTextFieldSegundoApellido.setText(stakeholderUpdateFrm.getSegundoApellido_usuario());;

        //jTextFieldTelefono.setText(Integer.toString(clienteUpdateFrm.getTelefono_cliente()));
        jPasswordFieldA.setText("");
        jPasswordFieldB.setText("");
        String tipoDocumento = stakeholderUpdateFrm.tipoDocumento.getTipoDocumento();
        jComboBoxTipoDocumento.setSelectedItem(tipoDocumento);
        String cargo = stakeholderUpdateFrm.cargo.getCargo();
        jComboBoxCargo.setSelectedItem(cargo);
        String rol = stakeholder.rol.getDescripcion_rol();
        jComboBoxRol.setSelectedItem(rol);
        cargarCargos();
        cargarTipoDocumento();
        cargarRol();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UsuarioFormjPanel1;
    private javax.swing.JPanel UsuarioFormjPanel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCargarDatos;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxCargo;
    private javax.swing.JComboBox<String> jComboBoxRol;
    private javax.swing.JComboBox<String> jComboBoxTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelNickname1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelNickname1;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JPasswordField jPasswordFieldA;
    private javax.swing.JPasswordField jPasswordFieldB;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIdentificacion;
    private javax.swing.JTextField jTextFieldNickname;
    private javax.swing.JTextField jTextFieldPrimerApellido;
    public javax.swing.JTextField jTextFieldPrimerNombre;
    private javax.swing.JTextField jTextFieldSegundoApellido;
    public javax.swing.JTextField jTextFieldSegundoNombre;
    private javax.swing.JLabel passAJLabel1;
    // End of variables declaration//GEN-END:variables
}
